export const hog="REYNAWA STUDIOS"
export const hog2="We're a full-service digital agency that believes being a Favorite brand is more valuable than just being a Famous one. We craft beautifully useful, connected ecosystems that grow businesses and build enduring relationships between brands and humans."
export const footerLogo="/images/Header-logo.png"
export const CompanyName="COMPANY"
export const CompanyName2="Reynawa Company"
export const CompanyName3="Ridha Company"
export const CompanyName4="Sadewa Company"
export const CompanyName5="reynawarsadewa@gmail.com"
export const CompanyName6=""

export const member="MEMBER"
export const member1="Reynawa"
export const member2="Ridha"
export const member3="Sadewa"
export const member4=""
export const member5=""
export const member6=""

export const follow="FOLLOW"
export const follow1="Reynawa Facebook"
export const follow2="Ridha Instagram"
export const follow3="Sadewa"
export const follow4=""
export const follow5=""